### PR TITLE
Accesses

### PR DESCRIPTION
**Pull request by vvarma**
Changes:
1. Add "accesses" in DataBuilderInfo and DataBuilderClassInfo
2. DataSetAccessor .get return guava Optional<Data>

### CODE REVIEW

**Comment by santanusinha** [comment]
I recommend not merging this due to the following reasons:
1) Pull requests should do one thing. I would like it to solve only accessible.
2) Formatter run in the same pull request.
3) Optional use does not look necessary here. Will increase latency for 99% percent of the cases that will not use accessible data at all.
4) Doc not updated.

**Comment by santanusinha** [comment]
Are you guys planning to fix this?

**Comment by vvarma** [comment]
Yes we are on it, but slightly shorthanded currently. Will sync up with gokul and plan it out.

**Comment by santanusinha** [comment]
No movement. Closing this.

**Pull request closed without merging**
